[package]
name = "boss-type"
version = "0.1.0"
authors = ["Louis Dureuil <louis.dureuil@xinra.net>"]

[dependencies]
worker-trait = { path = "../worker-trait" }
worker-type = { path = "../worker-type" }
